# 版本号
apiVersion: v1
# 控制器类型:副本控制器RC
kind: ReplicationController
metadata:
  # RC的名称,全局唯一
  name: tomcat
spec:
  # Pod副本期望数
  replicas: 1
  selector:
    # 符合目标的pod拥有此标签
    app: tomcat
  template:       # 根据此模板创建pod副本
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: "docker.io/tomcat:10-jdk11-openjdk"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080