# 版本号
apiVersion: v1
# 控制器类型:副本控制器RC
kind: ReplicationController
metadata:
  # RC的名称,全局唯一
  name: myweb
spec:
  # Pod副本期望数
  replicas: 2
  selector:
    # 符合目标的pod拥有此标签
    app: myweb
  template:       # 根据此模板创建pod副本
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - name: myweb
          image: kubeguide/tomcat-app:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080