spring:
  application:
    name: ${application_name:authorization-server}
  thymeleaf:
    enabled: true
    mode: HTML5
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
  datasource:
    url: jdbc:mysql://localhost:3306/train_db?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
eureka:
  client:
    registry-fetch-interval-seconds: 30 # 指示从eureka服务器获取注册表信息的频率（s）
    service-url:
      defaultZone: http://peer1:8801/eureka
  instance:
    instance-id: ${spring.application.name}-${random.int}
    lease-expiration-duration-in-seconds: 90 #定义服务失效时间
    lease-renewal-interval-in-seconds: 30 #续约时间
    hostname: peer1
server:
  port: 9000
logging:
  level:
    root: info
